/*int i <- 0;

const MAX = 200;

while (i <= MAX) {
    if i mod 2 = 0
        writeln("eh par ", i);
    else
        writeln("eh impar ", i);
    i <- i+1;
}
*/
/*
string nome <- "Gabriel";
string nomeAnterior;
nomeAnterior<- nome;
writeln(nome);
readln(nome);
writeln(nome = nomeAnterior);


char c <-'a';

writeln(c);

readln(c);

writeln(c);*/


int x <-5;
writeln(x);

readln(x);

writeln(x+5);

