/* Exemplo de Programa na linguagem L */


float n<-1;
string nome;
const MAXITER=10;
char x <- 0xFF;
int teste;

write("Digite seu nome: ", 5 < 5);
readln(nome);

float percentual;

if(nome = "jose") {

}

while 5 = 5 {
  percentual<-float(n)/MAXITER;
  writeln(percentual,": Ola' ",nome);
  n<-n+1;
}

if(n> 5) {
;;;;;;;;;
}
else if(n<3) {
    n <- .2;
    n <- float(int(MAXITER));
    n <- 5.5 * 3.5;
    x <- nome[5];
}
